language: python
python:
    - 2.6
    - 2.7
    - pypy
env:
    - DJANGO_VERSION=1.4.20
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.7.8
    - DJANGO_VERSION=1.8.1
matrix:
    exclude:
        - python: 2.6
          env: DJANGO_VERSION=1.7.8
        - python: 2.6
          env: DJANGO_VERSION=1.8.1
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install Django==$DJANGO_VERSION
script:
    - nosetests --with-coverage --cover-package=djproxy
    - nosetests integration_tests
after_success:
    - coveralls
